apiVersion: v1
kind: ConfigMap
metadata:
  name: v2ray-config
  namespace: v2ray
data:
  config.json: |
    {
      "log": {
        "loglevel": "warning",
        "access": "/dev/stdout",
        "error": "/dev/stderr"
      },
      "inbounds":,
            "decryption": "none"
          },
          "streamSettings": {
            "network": "tcp",
            "security": "tls",
            "tlsSettings": {
              "certificates": [
                {
                  "certificateFile": "/etc/v2ray/certs/tls.crt",
                  "keyFile": "/etc/v2ray/certs/tls.key"
                }
              ]
            }
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom"
        }
      ]
    }
